version: '3'
services:

  apps:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      express_monggose:
    restart: always
    volumes:
      - ./:/apps
      - /apps/node_modules
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - mongodb

  mongose:
    image: mongo:latest
    networks:
      express_monggose:
    volumes:
      - mongodb_apps:/data/db
      - mongodb_apps_config:/data/configdb
    ports:
      - ${MONGODB_PORT}:${MONGODB_PORT}

  mongo-express:
    image: ${MNG_DATABASE}
    ports:
      - ${ME_CONFIG_MONGODB_PORT}:${ME_CONFIG_MONGODB_PORT}
    environment:
      ME_CONFIG_MONGODB_SERVER: ${ME_CONFIG_MONGODB_SERVER}
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_CONFIG_BASICAUTH_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_CONFIG_BASICAUTH_PASSWORD}
    links:
      - mongodb
    restart: always
    networks:
      - express_monggose

networks:
  express_monggose:
    driver: bridge

volumes:
  mongodb_apps:
  mongodb_apps_config:
